### ISSUE TITLE
Level-first ordering for the sub-jobs

### ISSUE THREAD

**Issue by taoliaoleo** [google/privacy-sandbox-aggregation-service#237]
Got:
Subjob items with name:
```<aggregator>-<level>```

Expected:
```<level>-<aggregator>```, since higher level subjobs can only start when all lower level subjobs finish.

**Comment by haroonmoh** [comment]
Will there ever only be two aggregators or can there be more than 2? This would affect my implementation of this issue+

**Comment by haroonmoh** [comment]
Also is this the same as #234

**Comment by taoliaoleo** [comment]
You can choose to work on either one. Just add a comment "Duplicate with
issue<the other issue>" and close it.
[image: image.png]

**Comment by taoliaoleo** [comment]
Duplicate with #234

**Comment by taoliaoleo** [comment]
For each job, there are always two aggregators.
