### ISSUE TITLE
Add authentication and authorization

### ISSUE THREAD

**Issue by taoliaoleo** [google/privacy-sandbox-aggregation-service#242]

**Comment by hostirosti** [comment]
**Authentication**
- [ ] login with Google Sign-in https://firebase.google.com/docs/auth/web/google-signin
- [ ] login with Email/Password

**Authorization**
- [ ] Create Admin, Editor, Viewer roles
- [ ] Define Admin permissions
- [ ] Define Editor permissions
- [ ] Define Viewer permissions

**Comment by taoliaoleo** [comment]
For authorization, I think we can use the custom claims: https://firebase.google.com/docs/auth/admin/custom-claims. Example: https://dev.to/alvardev/firebase-firestore-rules-with-custom-claims-an-easy-way-523d

**Comment by haroonmoh** [comment]
I think we can close this.
